name: Release

description: Release packages

inputs:
  github-token:
    description: GitHub token
    required: true
  npm-token:
    description: NPM token
    required: true
  last-release:
    description: previous release commit hash
    required: true

runs:
  using: composite
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config user.name "GitHub Bot"
        git config user.email "ed@getlarge.eu"

    - name: Version
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      shell: bash
      run: npx nx affected --base=${{ inputs.last-release }} --target=version
