name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to bump packages to'
        required: true
        type: choice
        default: ''
        options:
          - path
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: set-shas
        uses: nrwl/nx-set-shas@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}
          github_token: ${{ secrets.GH_PAT }}

      - name: Test
        uses: ./.github/actions/test
        with:
          from: ${{ steps.set-shas.outputs.base }}

  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: [test]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GH_PAT }}

      - name: Release
        uses: ./.github/actions/release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          version: ${{ inputs.version }}
