name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - docs/*.md
      - .vscode/**
      - CHANGELOG.md
      - '**/CHANGELOG.md'
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - README.md
      - docs/*.md
      - .vscode/**
      - CHANGELOG.md
      - '**/CHANGELOG.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          # Shallow clones should be disabled for a better relevancy of Sonar analysis
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: set-shas
        uses: nrwl/nx-set-shas@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        uses: ./.github/actions/test
        with:
          from: ${{ steps.set-shas.outputs.base }}
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
          heroku-email: ${{ secrets.HEROKU_EMAIL }}

      # for now we just have one lib in the monorepo, so we can just use its version to qualify the sonar quality gate new code
      - name: Get nx-heroku version
        id: nx-heroku-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/nx-heroku

      # TODO: move in separate workflow
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.nx-heroku-version.outputs.current-version }}
